var twilio = require('twilio')
var firebase = require('firebase')
var storage = require('./database/storage.js')
var text = require('./texting/text.js')
var newPatient = require('./js/newPatient.js')
